version: '3'


services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
      DB_NUM: 0
    networks:
      - backend

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
