name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        stable: true
      id: go
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test ./... -v
