name: CI

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16
        stable: true
      id: go

    - name: Run a multi-line script
      run: |
        go mod download
        go test -v
